Programación para *Data Science*
============================

Intro101 - 05.1: Conceptos avanzados de Python
--------------------------------------

En este Notebook encontraréis dos conjuntos de ejercicios: un primer conjunto de ejercicios para practicar y que no puntuan, pero que recomendamos intentar resolver y un segundo conjunto que evaluaremos como actividad.


Además, veréis que todas las actividades tienen una etiqueta que indica los recursos necesarios para llevarla a cabo. Hay tres posibles etiquetas:

* <span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 3px; ">NM</span> **Sólo materiales**: las herramientas necesarias para realizar la actividad se pueden encontrar en los materiales de la asignatura. 

* <span style="font-family: Courier New; background-color: #ffcc5c; color: #000000; padding: 3px; ">EG</span> **Consulta externa guiada**: la actividad puede requerir hacer uso de herramientas que no se encuentran en los materiales de la asignatura, pero el enunciado contiene indicaciones de dónde o cómo encontrar la información adicional necesaria para resolver la actividad.

* <span style="font-family: Courier New; background-color: #f2ae72; color: #000000; padding: 3px; ">EI</span> **Consulta externa independente**: la actividad puede requerir hacer uso de herramientas que no se encuentran en los materiales de la asignatura, y el enunciado puede no incluir la descripción de dónde o cómo encontrar esta información adicional. Será necesario que el estudiante busque esta información utilizando los recursos que se han explicado en la asignatura.

Es importante notar que estas etiquetas no indican el nivel de dificultad del ejercicio, sino únicamente la necesidad de consulta de documentación externa para su resolución. Además, recordad que las **etiquetas son informativas**, pero podréis consultar referencias externas en cualquier momento (aunque no se indique explícitamente) o puede ser que podáis hacer una actividad sin consultar ningún tipo de documentación. Por ejemplo, para resolver una actividad que sólo requiera los materiales de la asignatura, puedéis consultar referencias externas si queréis, ya sea tanto para ayudaros en la resolución como para ampliar el conocimiento!


---

## Ejercicios y preguntas teóricas para la actividad

A continuación, encontraréis los **ejercicios y preguntas teóricas que debéis completar en esta actividad** y que forman parte de la evaluación de esta unidad.

### Ejercicio 1

Un número primo es aquél que solo es divisible por él mismo y por 1.

a) Escribe un código que compruebe si un número `x = 15` es solo divisible por 1 o por el mismo.  Escribe este código usando un iterador (un `for` o un `while`) que barra todos los valores desde `2` a `x-1`. Crea una variable `divisible`  que tenga por defecto valor `False` y asigne el valor `True` si a lo largo de la iteración encuentra un número natural divisible. Puedes usar el operador modulo `a % b` para saber si un numero `b` es divisible por `a`.

<span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 2px; ">NM</span>

In [ ]:
# Respuesta

In [ ]:
divisible = False
x=int(input('Introduce un número para saber si es o no primo:'))
for i in range (2,x):
  if x%i == 0:
    divisible = True
    break
print(divisible)

Introduce un número para saber si es o no primo:17
False



b) Convierte tu código anterior en una función que compruebe si el número del argumento es primo o no, devolviendo True is es primo y False si no es primo. Comprueba tu función con los valores 492366587, 492366585, 48947 y 2,

<span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 2px; ">NM</span>

In [ ]:
# Respuesta

In [ ]:
def Comprobar_numero_primo(n):
  primo = True
  for i in range (2,n):
    if n%i == 0:
      primo = False
      print('El número ',n ,'es divisible por ', i)
      break
  print('El número ', n, ' ¿es primo? ', primo)

Comprobar_numero_primo(492366587)
Comprobar_numero_primo(492366585)
Comprobar_numero_primo(48947)
Comprobar_numero_primo(2)

El número  492366587  ¿es primo?  True
El número  492366585 es divisible por  3
El número  492366585  ¿es primo?  False
El número  48947  ¿es primo?  True
El número  2  ¿es primo?  True



c) En el cálculo de la función anterior, una vez se ha encontrado un número que es divisible dentro del rango ya no tiene sentido comprobar el resto de números del rango. Por ejemplo si 10 ya es divisble entre 2, ya no hace falta probar de 3 en adelante pues ya sabemos que el número no es primo. 

Modifica la función anterior de la siguiente forma: 
- Una vez se encuentra el divisor, la iteración se interrumpe para no probar el resto de enteros. 
- La función devuelve
    - **Si es primo**: True
    - **Si no es primo**, el primer divisor mayor que 1.
    
Puedes hacer uso del comando *break* dentro de un bucle para interrumpir este, puedes consultar más información sobre break en la documentación de python [aquí](https://docs.python.org/2/tutorial/controlflow.html).

Comprueba tu función con los valores 492366585, 492366587, 48947 y 2,

<span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 2px; ">NM</span>

In [ ]:
# Respuesta

### Ejercicio 2

La Covid-19 es una enfermedad producida por la infección del virus SARS-CoV-2. La infección es transmisible de persona a persona y su contagiosidad depende de la cantidad del virus en las vías respiratorias. Si cada persona contagiada transmite la enfermedad a $\beta$ contactos en promedio por periodo de tiempo $t$, es posible estimar la evolución del contagio con un modelo matemático sencillo.

Para $t=1$día, las transmisiones en España se han estimado a partir de su histórico de las semanas de Febrero y Marzo del 2020 una $\beta = 0.35$ transmissiones por día por infectado.

Durante un periodo de tiempo (por ejempo un día $d$) la tasa de nuevos contagios se puede estimar como  una proporción al número de contagiados del periodo anterior $N$: 

$$ \Delta N = N_{1} - N = \beta \cdot N$$ (1)

Por tanto, podemos proyectar el número futuro de afectados como 

$$ N_{1} = N + \beta \cdot N = (1+\beta) \cdot N$$ (2) 

En dos días:

$$ N_{2} = (1+\beta) \cdot N_{1} = (1+\beta)^2 \cdot N$$  (3)

Y en general en D días tendremos 

$$N_{D} = (1+\beta)^D \cdot N$$  (4)
 
Asumiendo este sencillo modelo: 

a) Implementa una función de dos parámetros (N: población infectada inicial, D: número de días), que devuelva el cálculo de afectados para D días siguiendo la ecuación (4). Suponiendo una población afectada de 4250 (población afectada en españa a día 13 de Marzo de 2020), usa la función para calcular la población estimada en 1, 2, 7 y 30 días. 

<span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 2px; ">NM</span>

In [ ]:
# Respuesta

In [ ]:
def Afectados_Covid(n,d):
  afectados = round((1+0.35)**d*n)
  print ('El número de afectados en', d, 'días es', afectados, 'afectados')

Afectados_Covid(4250,1)
Afectados_Covid(4250,2)
Afectados_Covid(4250,7)
Afectados_Covid(4250,30)

El número de afectados en 1 días es 5738 afectados
El número de afectados en 2 días es 7746 afectados
El número de afectados en 7 días es 34732 afectados
El número de afectados en 30 días es 34546335 afectados



b) Sabiendo que los Servicios de Medicina Intensiva (SMI) disponen de 3363 camas para enfermos graves, y suponiendo que un 10% de los afectados por el covid-19 requerirán de SMI y una supervivencia del 2,5% (Exitus), escribe un código que calcule:
- El día en curso (Día)
- El total de afectados por el virus para cada día d (Afectados)
- El total de ingresados en SMI por el virus para cada día d (Críticos)
- El total de Exitus por el virus para cada día d (Exitus)
- Si los servicios de SMI no pueden aceptar los ingresados para cada día $d$ (Estado: indicando Saturación/No Saturación)

Imprime en pantalla la información de cada día durante una simulación de tres semanas, suponiendo que no hay recuperaciones, con una población afectada inicial 4250 y una $\beta = 0.35$ constante. 


<span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 2px; ">NM</span>

In [ ]:
# Respuesta


In [ ]:
#El día en curso (dia)

import datetime

hoy = datetime.date.today()
inicio_pandemia = datetime.date(2020,10,13)
dia = hoy-inicio_pandemia
dia= dia.days

#El total de afectados por el virus para cada día
n=4250
afectados = round((1+0.35)**dia*n)
print ('El número de afectados en día', dia, 'es', afectados, 'afectados')

#El total de ingresados en SMI por el virus para cada día d (críticos)
#Si los servicios de SMI no pueden aceptar los ingresados para cada día  d  (Estado: indicando Saturación/No Saturación)
criticos = 0.10*afectados
estado_saturacion = False
if criticos > 3363:
  estado_saturación = True
  print('Hay más enfermos críticos que camas en SMI')

#El total de Exitus por el virus para cada día d (exitus)
exitus = 0.025*afectados



El número de afectados en día 239 es 60001153602510126571134634629791744 afectados
Hay más enfermos críticos que camas en SMI


In [ ]:
#Bonus
#Imprime en pantalla la información de cada día hasta la fecha indicada, suponiendo que no hay recuperaciones, con una población afectada inicial 4250 y una  β=0.35  constante

def calcular_dia():
  import datetime
  a=int(input('Introduce el año: '))
  m=int(input('Introduce el mes: '))
  d=int(input('Introduce el día: '))
  fecha = datetime.date(a,m,d)
  inicio_pandemia = datetime.date(2020,3,13)
  dia = fecha-inicio_pandemia
  dia= dia.days
  return dia

def calcular_afectados(dia):
  n=4250
  afectados = round((1+0.35)**dia*n)
  return afectados

def calcular_criticos(afectados):
  criticos = 0.10*afectados
  return criticos

def calcular_exitus(afectados):
  exitus = 0.025*afectados
  return exitus

def calcular_estado(criticos):
  estado = 'No saturación'
  if criticos > 3363:
    estado = 'Saturación'
  return estado

dia=calcular_dia()
d=0
afectados=0
criticos=0
exitus=0
estado='No saturacion'
datos_dia = (d, afectados, criticos, exitus, estado)
datos_total = [('dia', 'afectados', 'criticos', 'exitus', 'estado')]
for d in range(0,dia+1):
  afectados = calcular_afectados(d)
  criticos = calcular_criticos(afectados)
  exitus = calcular_exitus(afectados)
  estado = calcular_estado(criticos)
  datos_total.append((d, afectados, criticos, exitus, estado))
print(datos_total)
  


Introduce el año: 2020
Introduce el mes: 05
Introduce el día: 1
[('dia', 'afectados', 'criticos', 'exitus', 'estado'), (0, 4250, 425.0, 106.25, 'No saturación'), (1, 5738, 573.8000000000001, 143.45000000000002, 'No saturación'), (2, 7746, 774.6, 193.65, 'No saturación'), (3, 10457, 1045.7, 261.425, 'No saturación'), (4, 14116, 1411.6000000000001, 352.90000000000003, 'No saturación'), (5, 19057, 1905.7, 476.425, 'No saturación'), (6, 25727, 2572.7000000000003, 643.1750000000001, 'No saturación'), (7, 34732, 3473.2000000000003, 868.3000000000001, 'Saturación'), (8, 46888, 4688.8, 1172.2, 'Saturación'), (9, 63298, 6329.8, 1582.45, 'Saturación'), (10, 85453, 8545.300000000001, 2136.3250000000003, 'Saturación'), (11, 115361, 11536.1, 2884.025, 'Saturación'), (12, 155738, 15573.800000000001, 3893.4500000000003, 'Saturación'), (13, 210246, 21024.600000000002, 5256.150000000001, 'Saturación'), (14, 283832, 28383.2, 7095.8, 'Saturación'), (15, 383173, 38317.3, 9579.325, 'Saturación'), (16, 5172

In [ ]:
#Imprime en pantalla la información de cada día durante una simulación de tres semanas, suponiendo que no hay recuperaciones, con una población afectada inicial 4250 y una  β=0.35  constante

dia = 21
n = 4250
beta = 0.35

def calcular_afectados(dia):
  afectados = round((1+beta)**dia*n)
  return afectados

def calcular_criticos(afectados):
  criticos = 0.10*afectados
  return criticos

def calcular_exitus(afectados):
  exitus = 0.025*afectados
  return exitus

def calcular_estado(criticos):
  estado = 'No saturación'
  if criticos > 3363:
    estado = 'Saturación'
  return estado

d=0
afectados=0
criticos=0
exitus=0
estado='No saturacion'
datos_dia = (d, afectados, criticos, exitus, estado)
datos_total = [('dia', 'afectados', 'criticos', 'exitus', 'estado')]
for d in range(0,dia+1):
  afectados = calcular_afectados(d)
  criticos = calcular_criticos(afectados)
  exitus = calcular_exitus(afectados)
  estado = calcular_estado(criticos)
  datos_total.append((d, afectados, criticos, exitus, estado))
print(datos_total)

[('dia', 'afectados', 'criticos', 'exitus', 'estado'), (0, 4250, 425.0, 106.25, 'No saturación'), (1, 5738, 573.8000000000001, 143.45000000000002, 'No saturación'), (2, 7746, 774.6, 193.65, 'No saturación'), (3, 10457, 1045.7, 261.425, 'No saturación'), (4, 14116, 1411.6000000000001, 352.90000000000003, 'No saturación'), (5, 19057, 1905.7, 476.425, 'No saturación'), (6, 25727, 2572.7000000000003, 643.1750000000001, 'No saturación'), (7, 34732, 3473.2000000000003, 868.3000000000001, 'Saturación'), (8, 46888, 4688.8, 1172.2, 'Saturación'), (9, 63298, 6329.8, 1582.45, 'Saturación'), (10, 85453, 8545.300000000001, 2136.3250000000003, 'Saturación'), (11, 115361, 11536.1, 2884.025, 'Saturación'), (12, 155738, 15573.800000000001, 3893.4500000000003, 'Saturación'), (13, 210246, 21024.600000000002, 5256.150000000001, 'Saturación'), (14, 283832, 28383.2, 7095.8, 'Saturación'), (15, 383173, 38317.3, 9579.325, 'Saturación'), (16, 517284, 51728.4, 12932.1, 'Saturación'), (17, 698334, 69833.40000000


c) Convierte el código anterior en una función que genere un archivo de texto con nombre `output.txt`, siguiendo este formato: 
```
Dia, Afectados, Críticos, Exitus, Estado
0, 4250, 425,  106, No Saturación
1, 5737, 573,  143, No Saturación
2, 7745, 774,  193, No Saturación
...
```
Con los parámetros de entrada $N$, $D$, $\beta$, camas SMI.

<span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 2px; ">NM</span>

In [ ]:
# Respuesta


In [ ]:
n=4000
beta=0.35
dia=21


def calcular_afectados(n,dia,beta):
  afectados = round((1+beta)**dia*n)
  return afectados

def calcular_criticos(afectados):
  criticos = 0.10*afectados
  return criticos

def calcular_exitus(afectados):
  exitus = 0.025*afectados
  return exitus

def calcular_estado(criticos):
  estado = 'No saturación'
  if criticos > 3363:
    estado = 'Saturación'
  return estado

from io import open

f = open('output.txt', 'w')
texto = 'dia' + '\t' + '\t' + 'afectados' + '\t' + '\t' + 'criticos' + '\t' + '\t' + '\t'  + 'exitus' +  '\t' + '\t' + '\t' + '\t' + 'estado' + '\t' + '\n' 
f.write(texto)

for d in range(0,dia+1):
  afectados = round(calcular_afectados(n,d,beta),2)
  criticos = round(calcular_criticos(afectados),2)
  exitus = round(calcular_exitus(afectados),2)
  estado = calcular_estado(criticos)
  texto = str(d) + '\t' + '\t' + str(afectados) + '\t' + '\t' + '\t' + str(criticos) + '\t' + '\t' + '\t' + '\t' + str(exitus) +  '\t' + '\t' + '\t' +'\t'+ str(estado) +'\n'
  f.write(texto)
f.close()
  
#hacemos un check para ver si está bien o no
f = open('output.txt', 'r')
texto2=f.read()
f.close()
print(texto2)


dia		afectados		criticos			exitus				estado	
0		4000			400.0				100.0				No saturación
1		5400			540.0				135.0				No saturación
2		7290			729.0				182.25				No saturación
3		9842			984.2				246.05				No saturación
4		13286			1328.6				332.15				No saturación
5		17936			1793.6				448.4				No saturación
6		24214			2421.4				605.35				No saturación
7		32689			3268.9				817.23				No saturación
8		44130			4413.0				1103.25				Saturación
9		59575			5957.5				1489.38				Saturación
10		80426			8042.6				2010.65				Saturación
11		108575			10857.5				2714.38				Saturación
12		146577			14657.7				3664.43				Saturación
13		197879			19787.9				4946.98				Saturación
14		267136			26713.6				6678.4				Saturación
15		360634			36063.4				9015.85				Saturación
16		486856			48685.6				12171.4				Saturación
17		657255			65725.5				16431.38				Saturación
18		887295			88729.5				22182.38				Saturación
19		1197848			119784.8				29946.2				Saturación
20		1617094			161709.4				40427.35				Saturación
21		218307

In [ ]:
texto = 'dia'+'\t'+'afectados'+'\t'+'criticos'+'\t'+'exitus'+'\t'+'estado'+'\n' 
print(texto)

dia	afectados	criticos	exitus	estado



### Ejercicio 3

Dado el siguiente diccionario:

In [ ]:
d = {"Alex":344334443, "Eva":5533443, "Cristina":443355, "Jonas":33223324}

Escribid una función que pregunte al usuario que introduzca el nombre de una persona y muestre por pantalla el nombre de la persona y su teléfono. 

Tened en cuenta que:

- La función debe controlar que el valor introducido por el usuario es un nombre que existe en el diccionario. En caso contrario, mostrará un mensaje de error ("El nombre introducido no corresponde a ninguna persona") y devolverá el valor False.
- Debéis tener en cuenta que el nombre de las personas que nos pasan por parámetro puede ser en minúsculas, mayúsculas o una combinación de ambas, y que debemos encontrar el número de teléfono aunque la capitalización de la cadena entrada por el usuario no sea exactamente la misma que hemos almacenado en el diccionario.
- Suponed que  no hay acentos en los nombres.

Nota 1: Para realizar la actividad, tendréis que capturar un texto que entrará el usuario. Consultad la [documentación oficial de la función input](https://docs.python.org/3/library/functions.html#input) para ver cómo hacerlo.

Nota 2: También tendréis que pensar cómo tratar el hecho de que el usuario pueda utilizar mayúsculas y minúsculas en la escritura del nombre en el diccionario. ¡Os animamos a usar un buscador para intentar encontrar alguna alternativa para resolver este subproblema! ¡Recordad citar las referencias que hayáis usado para resolverlo!

<span style="font-family: Courier New; background-color: #ffcc5c; color: #000000; padding: 3px; ">EG</span>

In [ ]:
d = {"Alex":344334443, "Eva":5533443, "Cristina":443355, "Jonas":33223324}

# Respuesta

def obtener_telefono():
  nombre = input ('Escribe un nombre: ')
  nombre=nombre.capitalize()
  if d.get(nombre) == None:
    print("El nombre introducido no corresponde a ninguna persona")
    return False
  else:
    print(nombre, ': ', d.get(nombre))
    return True
  

obtener_telefono()

Escribe un nombre: cristina
Cristina :  443355


True

Referencias consultadas:

*Incluir aquí las referencias*

###  Ejercicio 4

Python dispone de un **idiom** muy útil conocido como `list comprehension`. Utilizando este **idiom**, proporcionad una expresión que devuelva las listas siguientes.

Nota: Para realizar esta actividad necesitaréis investigar qué son las `list comprehension` y qué sintaxis utilizan. Para ello, se recomienda en primer lugar que utilicéis un buscador para encontrar información genérica sobre esta construcción. Después, os recomendamos que consultéis stackoverflow para ver algunos ejemplos de problemas que se pueden resolver con esta construcción.


[stackoverflow](https://stackoverflow.com/) es un sitio de preguntas-y-respuestas muy popular entre programadores. Veréis que para la gran mayoría de las dudas que tengáis, habrá alguien que ya les habrá tenido (y consultado) anteriormente! Así pues, más allá de preguntar vosotros mismos las dudas allí (nosotros ya tenemos el foro del aula para ello!), consultar esta web os permitirá ver qué soluciones proponen otros programadores a estas dudas. A menudo habrá más de una solución a un mismo problema, y podréis valorar cuál es la más adecuada para vuestro problema.

Para ver ejemplos de problemas que son adecuados para resolver con **list comprehensions**, os recomendamos leer las siguientes páginas:
* https://stackoverflow.com/questions/12555443/squaring-all-elements-in-a-list
* https://stackoverflow.com/questions/18551458/how-to-frame-two-for-loops-in-list-comprehension-python
* https://stackoverflow.com/questions/24442091/list-comprehension-with-condition
* https://stackoverflow.com/questions/41676212/i-want-to-return-only-the-odd-numbers-in-a-list
* https://stackoverflow.com/questions/4260280/if-else-in-a-list-comprehension

<span style="font-family: Courier New; background-color: #ffcc5c; color: #000000; padding: 3px; ">EG</span>


a) Una lista con los valores $4 x^2$ donde $x$ es cada uno de los números de la lista `list_1`:

In [ ]:
list_1 = [1, 2, 3, 4, 5, 6, 7, 8, 9]

# Respuesta

list_2 = [4*x**2 for x in list_1]
print (list_2)

[4, 16, 36, 64, 100, 144, 196, 256, 324]


b) Una lista con los valores $x/(x+1)$ donde $x$ es cada uno de los números de la lista `list_1`:

In [ ]:
list_1 = [1, 2, 3, 4, 5, 6, 7, 8, 9]

# Respuesta

list_2 = [round(x/(x+1),2) for x in list_1]
print(list_2)

[0.5, 0.67, 0.75, 0.8, 0.83, 0.86, 0.88, 0.89, 0.9]


c) Una lista con los valores $4x^2/(4x^2-1)$ donde $x$ es cada uno de los números de la lista `list_1`:

In [ ]:
list_1 = [1, 2, 3, 4, 5, 6, 7, 8, 9]

# Respuesta

list_2 = [round(4*x**2/(4*x**2-1),2) for x in list_1]
print(list_2)


[1.33, 1.07, 1.03, 1.02, 1.01, 1.01, 1.01, 1.0, 1.0]


### Ejercicio 5

Las funciones `lambda` son formas de expresar y definir funciones pequeñas sin necesidad de usar el constructor `def funcion():`.

Lee sobre las funciones lambda, por ejemplo [aquí](https://www.w3schools.com/python/python_lambda.asp) o [aquí](https://realpython.com/python-lambda/)

Escribe una función $f$ con argumento $n$, $f(n)$, que **devuelva una función** lambda, que esta a su vez devuelva $n$ copias de una cadena de caracteres en su argumento: 

<span style="font-family: Courier New; background-color: #f2ae72; color: #000000; padding: 3px; ">EI</span>

In [ ]:
# Respuesta

def f(n): 
    # Definir de la función usando una método lambda
    texto = 'hola'
    respuesta = texto
    for i in range(1,n):
        respuesta = respuesta + ' ' + texto
    return(respuesta)

r = f(5)
print(r)
#r("hola")  # Donde deberíamos ver 5 copias del literal "Hola "

hola hola hola hola hola


In [ ]:
def f(n):
    # Definir la función usando una método lambda
    respuesta = lambda texto: texto*n
    return(respuesta)

r = f(5)
print(r('hola'))

holaholaholaholahola


In [ ]:
suma = lambda a,b: a+b
print(suma(5,6))


11


### Ejercicio Opcional

Existe una expresión atribuida a John Wallis (1616) para la estimación del valor de $\pi$, consistente en: 

$$
\frac{\pi}{2} = \prod_{n=1}^{N} (\frac{4n^2}{4n^2 - 1})
$$
si $N$ es suficientemente grande  $N \to \infty$. 

Escribe una función que, dado una aproximación N, calcule una estimación de $\pi$ siguiendo la fórmula de Wallis. 



**Consideraciones:**

- Investigad las funciones map, reduce
- También podéis usar una list comprehension
- Las funciones lambda os pueden ser útiles

<span style="font-family: Courier New; background-color: #f2ae72; color: #000000; padding: 3px; ">EI</span>

In [ ]:
# Respuesta

In [9]:
def calcular_pi(n):
  pi = 2 #punto de partida al despejar pi en la ecuación de John Wallis
  for n in range(1,n+1):
    pi = pi*4*n**2/(4*n**2-1)
  return pi

print(calcular_pi(500000))


3.1415910827956552
